name: C/C++ CI - Windows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout test case
      uses: actions/checkout@v3
      with: 
        repository : ubsuny/WorldOfTextCraftInputsFall2022 
        ref: main
        path: './WorldOfTextCraftInputsFall2022'
    - name: catit
      run: cat WorldOfTextCraftInputsFall2022/problem1_inputs.txt     
    - name: make
      run: make
    - name : run_none
      run: ./WorldOfTextCraft
    - name: run
      run: cat WorldOfTextCraftInputsFall2022/problem1_inputs.txt |  ./WorldOfTextCraft ThreeStooges.txt Shemp.txt ShempAttacks.txt

