name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout test case
      uses: actions/checkout@v3
      with: 
        repository : ubsuny/WorldOfTextCraftInputsFall2022 
        ref: main
        path: './WorldOfTextCraftInputsFall2022'
    - name: make
      run: make
    - name: run
      run: ./WorldOfTextCraft ThreeStooges.txt Shemp.txt ShempAttacks.txt < WorldOfTextCraftInputsFall2022/problem1_inputs.txt

